name: Run Text Myself Script
on:
  workflow_dispatch:
  schedule:
    - cron: "0 17 * * *"
    - cron: "0 0 * * *"

jobs:
  text-myself:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          repository: "adeshpande03/Text-Yourself-Python"
          # Replace <your_github_username> with your actual GitHub username

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x" # Replace '3.x' with the specific version of Python you need, if necessary

      - name: Run main.py
        run: python main.py
        env:
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
          EMAIL: ${{ secrets.EMAIL }}
          PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
